name: Gatsby Deploy

on:
  push:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Github Config
        run: |
            git config --global user.name "teo523"
            git config --global user.email "teodoro.dan@gmail.com"
      - name: Deploy
        run: npm run deploy:ci
